# Generated by Django 5.2.1 on 2025-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=100)),
                ('type_key', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('315', '315MHz'), ('433', '433MHz')], max_length=6)),
                ('trasnponder', models.CharField(max_length=100)),
                ('immo_part_replacement', models.CharField(max_length=100)),
            ],
        ),
    ]
