# Generated by Django 5.2.1 on 2025-05-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='frequency',
            field=models.CharField(max_length=6),
        ),
    ]
