# Generated by Django 5.2.1 on 2025-05-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_lines_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='frequency',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
