# Generated by Django 5.2.1 on 2025-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_lines_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lines',
            old_name='trasnponder',
            new_name='transponder',
        ),
        migrations.AlterField(
            model_name='lines',
            name='frequency',
            field=models.CharField(blank=True, choices=[('315', '315MHz'), ('433', '433MHz')], max_length=3, null=True),
        ),
    ]
