# Generated by Django 5.2.1 on 2025-05-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_rename_trasnponder_lines_transponder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo do Veículo')),
                ('ano', models.CharField(max_length=20, verbose_name='Ano')),
                ('tipo_chave', models.CharField(max_length=100, verbose_name='Tipo de Chave')),
                ('sistema', models.CharField(max_length=100, verbose_name='Sistema')),
                ('transponder', models.CharField(max_length=100, verbose_name='Transponder')),
                ('frequencia', models.CharField(choices=[('315', '315 MHz'), ('433', '433 MHz'), ('None', 'Sem Frequência')], max_length=5, verbose_name='Frequência')),
                ('immo', models.CharField(max_length=100, verbose_name='IMMO')),
            ],
        ),
        migrations.DeleteModel(
            name='Lines',
        ),
    ]
