# Generated by Django 5.2.1 on 2025-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_veiculo_delete_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='frequencia',
            field=models.CharField(choices=[('315', '315 MHz'), ('433', '433 MHz')], max_length=3, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
    ]
