# Generated by Django 5.2.1 on 2025-05-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_veiculo_frequencia_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='newVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('ano', models.CharField(blank=True, max_length=20, verbose_name='Ano')),
                ('sistema', models.CharField(blank=True, max_length=100, verbose_name='Sistema')),
                ('frequencia', models.CharField(blank=True, choices=[('', '---------'), ('315', '315MHz'), ('433', '433MHz')], max_length=3, verbose_name='Frequência')),
                ('add_key', models.CharField(blank=True, choices=[('', '---------'), ('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=10, verbose_name='Add Key')),
                ('read_password', models.CharField(blank=True, choices=[('', '---------'), ('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=10, verbose_name='Read Password')),
                ('remote_learning', models.CharField(blank=True, choices=[('', '---------'), ('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=10, verbose_name='Remote Learning')),
                ('type_key', models.CharField(blank=True, max_length=100, verbose_name='Key Type')),
                ('transponder', models.CharField(blank=True, max_length=100, verbose_name='Transponder')),
                ('immo_part_replacement', models.CharField(blank=True, max_length=100, verbose_name='IMMO Part Replacement')),
            ],
        ),
    ]
