# Generated by Django 5.2.1 on 2025-05-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_newveiculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newVeiculo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='immo',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='add_key',
            field=models.CharField(blank=True, choices=[('', '---------'), ('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=10, verbose_name='Add Key'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='immo_part_replacement',
            field=models.CharField(blank=True, max_length=100, verbose_name='IMMO Part Replacement'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='read_password',
            field=models.CharField(blank=True, choices=[('', '---------'), ('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=10, verbose_name='Read Password'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='remote_learning',
            field=models.CharField(blank=True, choices=[('', '---------'), ('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=10, verbose_name='Remote Learning'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('', '---------'), ('315', '315MHz'), ('433', '433MHz')], max_length=3, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='sistema',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sistema'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_chave',
            field=models.CharField(blank=True, max_length=100, verbose_name='Key Type'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='transponder',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transponder'),
        ),
    ]
