# Generated by Django 5.2.1 on 2025-05-13 13:43

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_veiculo_key_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='add_key',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Add Key'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('', '---------'), ('315', '315 MHz'), ('433', '433 MHz')], max_length=3, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='immo_part_replacement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Substituição da Peça IMMO'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='key_lost',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Key Lost'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='read_password',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Read Password'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='remote_learning',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Remote Learning'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_chave',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Chave'),
        ),
    ]
